version: '3'
services:
  web:
    build: 'web'
    ports:
      - "8000:8000"
  celery:
    build: 'web'
    command: 'pipenv run celery -A roles.app.celery worker'
  rabbitmq:
    image: rabbitmq:3
    volumes:
      - mqdata:/var/lib/rabbitmq
  postgres:
    image: postgres:10
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  mqdata:
