version: '3'
services:
  web:
    build: 'web'
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
      - celery
  celery:
    build: 'web'
    command: 'pipenv run watchmedo auto-restart -d roles/ -p "*.py" -- celery -A roles.celery.celery worker'
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:4
  postgres:
    image: postgres:10
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
