"""Add Action table.

Revision ID: 4cbe8e432c6b
Revises: 7b08cf35abd9
Create Date: 2018-07-27 20:05:30.976453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbe8e432c6b'
down_revision = '7b08cf35abd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=120), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_uid'), 'action', ['uid'], unique=False)
    op.create_table('crawl_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_error')
    op.drop_index(op.f('ix_action_uid'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###
