"""Initial database

Revision ID: 7b08cf35abd9
Revises: 
Create Date: 2018-07-27 19:45:26.456443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b08cf35abd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nid', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('term', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_nid'), 'network', ['nid'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('task_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_task_id'), 'crawl', ['task_id'], unique=False)
    op.create_table('network_user',
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('network_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network_user')
    op.drop_index(op.f('ix_crawl_task_id'), table_name='crawl')
    op.drop_table('crawl')
    op.drop_table('user')
    op.drop_index(op.f('ix_network_nid'), table_name='network')
    op.drop_table('network')
    # ### end Alembic commands ###
