"""Add num_fully_anon to Crawl

Revision ID: 95e11f84f7e9
Revises: f89c5012fd5d
Create Date: 2018-08-06 18:31:22.679039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e11f84f7e9'
down_revision = 'f89c5012fd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('num_fully_anon', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl', 'num_fully_anon')
    # ### end Alembic commands ###
