"""Add weight to RoleProportion

Revision ID: f89c5012fd5d
Revises: dae74ff90530
Create Date: 2018-08-02 23:28:46.403711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89c5012fd5d'
down_revision = 'dae74ff90530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_proportion', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_proportion', 'weight')
    # ### end Alembic commands ###
