"""Add analysis tables

Revision ID: fcdebddd1d72
Revises: bb3f9dae30cf
Create Date: 2018-08-01 18:38:07.258525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdebddd1d72'
down_revision = 'bb3f9dae30cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('session_gap', sa.Float(), nullable=False),
    sa.Column('role_count', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('proportion_smoothing', sa.Float(), nullable=False),
    sa.Column('role_smoothing', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_weight',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'type_id')
    )
    op.create_table('role_proportion',
    sa.Column('uid', sa.String(length=120), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('uid', 'analysis_id', 'role_id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=120), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_uid'), 'session', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_uid'), table_name='session')
    op.drop_table('session')
    op.drop_table('role_proportion')
    op.drop_table('action_weight')
    op.drop_table('role')
    op.drop_table('analysis')
    # ### end Alembic commands ###
